### ISSUE TITLE
Don't depend on Intl polyfill in bower

### ISSUE THREAD

**Issue by jods4** [aurelia/i18n#120]
This library pulls in an `Intl` polyfill.
It would be nice if this was not pulled in automatically by Bower, because now I have to take extra steps to remove it from my build.

I would prefer if the documentation said `Intl` was required and pointed to a polyfill if required, but if the responsability to include it was left on the developper. As more and more browsers support standards (support for `Intl` goes back to IE11) polyfills become increasingly unnecessary. 

There is a precedent for handling polyfills that way: Aurelia depends on `Promise` but it is the dev responsibility to include a polyfill if his target browser doesn't support it.

**Comment by zewa666** [comment]
Actually we do not really depend on the polyfill but load it on demand. The only issue appears when you bundle and might need the polyfill for certain visitors, in that case you'd always have it.

The reason for the auto-magic-inclusion was to make getting started with the plugin as easy as possible.

**Comment by jods4** [comment]
@zewa666 yes, this was exactly my point!
I use bower and I currently have to make an exception _not_ to include Intl.

Given this: http://caniuse.com/#feat=internationalization I think it's reasonable to assume it's there and ask the few unlucky devs to take an extra step _to include_ Intl instead.

**Comment by zewa666** [comment]
Yep I fully understand you @jods4 and would happily remove that step, but the reason why we did it is that as soon as I created the initial feature, tons of users came back to reply they had issues with their implementations. And the reason was usage of unsupported browsers.

Another reason is Nodes implementation of the Intl.API. In order to avoid a lot of hickups, loading the polyfill makes work with it consistent across Front and Backend. Look here for more details https://github.com/andyearnshaw/Intl.js/#intljs-and-node
