### ISSUE TITLE
Use the df value convertor for ISO8601 strings

### ISSUE THREAD

**Issue by TimBailey99** [aurelia/i18n#153]
When loading data from the server via JSON I'm sending them as ISO8601 strings.  Currently when I try and use the df value converter on these strings I get "RangeError: Provided date is not in valid range."

I propose to support automatic conversion to Date objects when a "date-like" string is passed via the df.

I have a pull request ready if this is a reasonable feature.

**Comment by zewa666** [comment]
First of all I wonder why you get that error since [this line](https://github.com/aurelia/i18n/blob/master/src/df.js#L15) should normally cover the string case and just return it as is. So could you create a small gist depicting the issue in order to fix it?

The automatic conversion is possible yet error prone. What are you doing in case of `1.7.2016`. Is that first of July or 7th of January?

A typical scenario is to add a reviver to your json parse call, which would transform the string, according to your needs into a Date and then pass the date on to the DfValueConverter. Another approach would be to build your custom ValueConverter for Dates and pipe the result to Df. An example using Moment.JS can be [found here](http://jdanyow.github.io/aurelia-converters-sample/#simple-converters).

We could of course include said VC as part of the I18N plugin, but I feel hesitant to add yet another library to the stack.

**Comment by TimBailey99** [comment]
The line you refer to basically returns immediately if the values is a string AND is blank.
If the string is a date, I want it to be displayed not as is, but in locale format.

ie if the date is ISO 2016-09-06 and the locale is en-AU, then it should display as 06/09/2016 etc

What I propose is specific support for only Date.parse ISO8601/RFC2822 strings (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse), which can be passed directly to the Date constructor.

I'm currently using the Aurellia-Api to REST the data from the server, I did see the general suggestion to reviver but not sure how i can access that via the api.
I guess i could also create a VC for converting from ISO Format to date and then piping to the Df, but that would clutter up the markup.

**Comment by zewa666** [comment]
oh ok so its just about the ISO8601. I guess the UTC timehandling part of it will be enough to support different timezones / winter/summer time.

Ok in that case we should only respect dates and iso8601 conform strings and for everything else return the value as is. We should also add a note about this in the readme.

I'd be glad to take a look at your PR so we can work out the details then based on it.

**Comment by TimBailey99** [comment]
I added the pull request, please have a look.
I'm not sure that anything other that simple date strings makes sense, ie 2016-09-07 is good, but full datetimes then show in the timezone of the browser/OS which may or may not be what you are expecting. 

#154

**Comment by TimBailey99** [comment]
Hmm, pesky dates.

So the tests all pass on my windows machine.  Its a fresh install and I'm sure I've not tweaked the windows date formatting settings.

The tests fail on CircleCi with the following error:

> Chrome 50.0.2661 (Linux 0.0.0) dfvalueconverter tests should return formated string if ISO8601 date string value given LOCAL time AU FAILED
> 	Expected '5/9/2016' to be '05/09/2016'.

Assuming that on linux the default date format for AU is d/M/yyyy not the dd/MM/yyyy that is on windows.  
Any suggestions on how to deal with this situation?

**Comment by zewa666** [comment]
Regarding your issue with Linux:
Adding options where you specify the expected result should fix it https://github.com/aurelia/i18n/commit/e4771df9cb8182be2ccf610238057967267c611e#diff-7d177e607b2505853c4d3b6a10d43cd7R88

besides that I've still reverted to taking the TimeZones in as it at least is a use case for some apps I've already written and seen. E.g. think of a event calendar showing meeting dates and times to an international audience. Now I'd really like to know what the time of the meeting is across the world, in its own timezone. Regarding the browserOS, well thats expected, we can't second guess the users intention of why he set up what he has. If the dev wants to force it, he can always override the [timezone setting](https://github.com/aurelia/i18n/commit/e4771df9cb8182be2ccf610238057967267c611e#diff-7d177e607b2505853c4d3b6a10d43cd7R81) and force something.

So I'm more for being open for all use cases instead of forcing you down one path. Lets see how it evolves, we always can change back if there is an issue.

Thanks for the contribution, I've merged your PR manually to add the fixes and to make sure the title is according to our guidelines, so next time it will be seen in the changelog :)
