### ISSUE TITLE
i18n support and customElement/aurelia-materialize-bridge

### ISSUE THREAD

**Issue by mar9000** [aurelia/i18n#169]
**I don't know if I'm submitting a bug report or a feature request**
- **Library Version:** 1.2.0
- **Operating System:** Linux Mint
- **Node Version:** 6.2.0
- **JSPM** 0.16.42
- **Browser:** all
- **Language:** ESNext

In i18n.updateValue() an attribute, in my case `md-label`, gets updated correctly with `t="[md-label]email"` when the locale changes. However parts of the custom element that depend on that attribute (in this case a 'label' element of the `md-input` element) are not updated and as far as I know it's possibile to listed to setAttribute() only throught its redefinition.

I'm referencing this issue of the aurelia-materialize-bridge opened by myself. I'm not sure if it could be also an aurelia-i18n bug https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/298
**Should i18n.updateValue() use some sort of notification after node.setAttribute()?**

**Comment by mar9000** [comment]
This is definitely an aurelia-i18n bug.
Into the issue of the aurelia-materialize-bridge mentioned above you can find a testing project to reproduce the problem.
Basically everything is working with attributes without dash, like `foovalue`, the problem araises only with attributes like `foo-value`, and all the `md-*` attribute from the bridge. In `i18n.updateValue()` at this point 
```javascript
  if (node.au && node.au.controller && node.au.controller.viewModel && node.au.controller.viewModel[attr]) {
    node.au.controller.viewModel[attr] = this.tr(key, params);
  } else {
    node.setAttribute(attr, this.tr(key, params));
  }
```
the attributes with a dash exist in `node.au.controller.viewModel` but as for instance `fooValue` whereas the attr value is `foo-value`, indeed the code goes through `node.setAttribute()` updating the attribute but not  HTML content generated from that attribute.

**Comment by zewa666** [comment]
thanks for digging in, I'll take a look at it, clearly haven't tested for that use-case, which is a more than valid one.

**Comment by zewa666** [comment]
ok there is a fix in place for that which is scheduled for the next release

**Comment by zewa666** [comment]
New release is out please check if this fixes your issue @mar9000

**Comment by Thanood** [comment]
@mar9000 @zewa666 
I've cloned https://github.com/Ullfis/esnext-i18n-errors and updated. The error is gone in this repo. 👍 

There are multiple variations in this test repo.
This variation does not update: `md-value.two-way="i18n.tr('FirstName')"`.
I'm not sure if it should, because the return value of `i18n.tr('FirstName')`  is bound, right?

**Comment by mar9000** [comment]
This should be asked to  @Ullfis that actually is the one that set up the repo.

**Comment by zewa666** [comment]
using `i18n.tr('FirstName')` is just a one-off translation and shouldn't be directly consumed by templates. The way to use them there is either with the attribute ( i18n / t ), the ValueConverter ( | ) or the BindingBehavior ( & ).
So yep that is expected. Nevertheless, it's not part of this issue and if new problems appear I'd ask you to create a new dedicated issue for it.

Thanks @Thanood for verifying the dashed-case fix. @mar9000 since you're the one opening the issue I'd really like to ask you also to give it a quick look, so we can close this issue.

**Comment by mar9000** [comment]
Test successful. For me you can close this issue. Thx for fixing it.

**Comment by zewa666** [comment]
Thanks for Reporting and testing it.
