### ISSUE TITLE
Null values don't use default language

### ISSUE THREAD

**Issue by RWOverdijk** [aurelia/i18n#170]
**I'm submitting a bug report**

When the value for a translation is null, aurelia-i18n uses the stringified version "null" in stead of the value in the fallback language.

I've used a couple of tools, one of which is webtranslateit. In all of the tools I've used, empty translations get set as null. It would be _very_ nice if i18n then falls back to the fallbackLanguage (which is our master file, english.).

**Comment by zewa666** [comment]
@RWOverdijk hi this is intentional by i18next. See the [official options docs](http://i18next.com/docs/options/) and search for `returnNull`. Setting this to false in your plugin configuration on the i18next object, should solve your issue.

Also note the `returnEmptyString` property, which comes in handy from time to time as well.

**Comment by zewa666** [comment]
I'm gonna close this one for now, if you @RWOverdijk have any other objections we can reopen any time
