### ISSUE TITLE
Module ''i18next'' has no default export

### ISSUE THREAD

**Issue by enrico-padovani** [aurelia/i18n#182]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
4.0.2

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
all

* **Language:**
TypeScript 2.1.1

**Current behavior:**
When running webpack dev it prints out: [my_local_path]\node_modules\aurelia-i18n\dist\aurelia-i18n.d.ts:1:8
    Module ''i18next'' has no default export.

**Expected/desired behavior:**
No errors

**Comment by zewa666** [comment]
thanks for the feedback. This issue is already noted and tracked here via a PR
https://github.com/aurelia/i18n/pull/171

**Comment by zewa666** [comment]
@enrico-padovani I've updated the docs section on how to get typescript up and running properly. Please give it a read and see whether this fixes your issue. I can just second guess its either an issue due to allowSyntheticDefaultImporting or a missing typedefinition, both which are described now even clearer https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md

**Comment by enrico-padovani** [comment]
By setting allowSyntheticDefaultImporting to true does solve the problem. Thanks for the help!
