### ISSUE TITLE
uf() uses float for currency? uf100()?

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/i18n#215]
uf() parses a string into a number. It assumes currency is kept in float as written in the document.

```
 uf(number, locale?): number {
    ...
    // return real number
    return Number(result);
}
```

But you know it is impossible to keep accuracy with float.

```
> Number("10.20")*100
1019.9999999999999
```

I think the current uf() causes problems if people use it for currency. Should i18n plugin have a method that converts currency into integers or BCD? 

For example, uf100("10.20") would do as Number("10") * 100 + Number("20") --> 1020.

Intl.NumberFormat can represent the 1020 as "10.20" like this. Seems no error.

```
> new Intl.NumberFormat("en", { style: 'currency', currency: "USD"}).format(1020/100);
"$10.20"
```

**Comment by zewa666** [comment]
Hi @HIRANO-Satoshi the use case for uf was simply to unformat numbers and represent them without a style, perhaps even pass them on to other formatters. Your use case is valid though. uf100 would as such just remove two decimal places right?

So what you propose is a function that removes the decimal place at all? Like over here https://github.com/aurelia/i18n/blob/master/src/i18n.js#L82 to include `,` as well and the user then would have to divide by himself? Or would you pass in another parameter for the definition of how many decimal places you want as a result?

Nevertheless of the outcome, I'd leave uf as it is and just introduce a new function, as you proposed, just not sure whether uf100 is to specific and could be generalized instead.

Would you be willing to provide a PR for what you had in mind so far, so that we can take a look and fiddle around on a real implementation?

**Comment by HIRANO-Satoshi** [comment]
There is no browser support for parsing numbers by locales. *parseFloat("٣٣٫٣٣")* does not work, for example. 

i18next does not have locale based parsing of numbers, right? 

I think globalize is needed.

**Comment by zewa666** [comment]
Yes that's true and it's clearly not the intention to replicate other plugins, so people needing specific support should head out to numeraljs or globalize

**Comment by HIRANO-Satoshi** [comment]
I see.

Here is an example of parsing currency and converting it to an integer having currency*1000 for avoiding error of floating point numbers. 1000 is because some currencies have three digits after decimal point.
Although it is not suitable to a-i18n, it might be useful for somebody.

big.js is a small library for arbitrary-precision decimal arithmetic.
You can use *int1000* and *bigDecimal* for calculation.

```
        import * as Big from 'big.js';
        import * as Globalize from 'globalize';

        let locale = "en";   // "ar", "ja"...
        let enParser = Globalize(locale).numberParser();
        let floatNum = enParser( "12,735.00" );
        
        let bigDecimal = new Big(floatNum);
        let bigDecimal1000 = bigDecimal.times(1000);
        var int1000 = parseInt(bigDecimal1000.toFixed(0));  // integer

        // any calculation on int1000
```

I wrote a value converter which could convert "٣.٣٣٣٫٣٣" into 3333.33 by observing numbers using only Intl.NumberFormat. 
It seems working on almost all locales but it is complicated. I think globalize is a realistic solution.

**Comment by zewa666** [comment]
After more thinking, and as our conversation turned out, I definitely think this is supposed not to be part of the plugin by itself. Your information provided above will definitely help others, who might try to build something similar but honestly I suspect its that often needed. Therefore I'm going to close this issue for know. If we get more feedback or further requests we can always reopen. Thanks again for your contribution @HIRANO-Satoshi

**Comment by HIRANO-Satoshi** [comment]
okay. Thanks for consideration.
